# Generated by Django 4.1.1 on 2022-10-07 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_url', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_hash', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(max_length=30, unique=True)),
                ('url_hash', models.CharField(max_length=15, unique=True)),
                ('url_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='link_transformer.url')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='link_transformer.user')),
            ],
        ),
        migrations.CreateModel(
            name='LinkClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='link_transformer.userlink')),
            ],
        ),
        migrations.AddConstraint(
            model_name='userlink',
            constraint=models.UniqueConstraint(fields=('url_id', 'user_id', 'short_url'), name='unique user link record'),
        ),
        migrations.AddConstraint(
            model_name='userlink',
            constraint=models.UniqueConstraint(fields=('url_id', 'user_id'), name='unique user link'),
        ),
    ]
